useDotenv: true
org: rafet
app: rafet-test-api
service: eCommerceApp

stages:
  default:
    params:
      customersTableName: "customers-table-${sls:stage}"
      ordersTableName: "orders-table-${sls:stage}"

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [CustomersTable, Arn]
            - arn:aws:dynamodb:${self:provider.region}:*:table/products-table-dev
            - Fn::GetAtt: [OrdersTable, Arn]
            - arn:aws:dynamodb:${self:provider.region}:*:table/orders-table-dev
        - Effect: Allow
          Action:
            - cognito-idp:AdminUpdateUserAttributes
          Resource:
            - arn:aws:cognito-idp:${self:provider.region}:${aws:accountId}:userpool/${env:USER_POOL_ID}
  environment:
    CUSTOMER_TABLE: ${param:customersTableName}
    PRODUCTS_TABLE: "products-table-dev"
    CATEGORIES_TABLE: "categories-table-dev"
    ORDERS_TABLE: ${param:ordersTableName}
    STRIPE_SECRET_KEY: ${env:STRIPE_SECRET_KEY}
    STRIPE_WEBHOOK_SECRET: ${env:STRIPE_WEBHOOK_SECRET}
    USER_POOL_ID: ${env:USER_POOL_ID}    

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: products
          method: get
          cors: true
      - http:
          path: products/{productId}
          method: get
          cors: true
      - http:
          path: checkout
          method: post
          cors: true
      - http:
          path: webhook
          method: post
          cors: true
          integration: lambda-proxy
      - http:
          path: orders
          method: get
          cors: true
      - http:
          path: orders/{orderId}
          method: get
          cors: true
      - http:
          path: categories
          method: get
          cors: true
      - http:
          path: profile
          method: get
          cors: true
      - http:
          path: profile
          method: patch
          cors: true
          

resources:
  Resources:
    CustomersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: customerId
            AttributeType: S
        KeySchema:
          - AttributeName: customerId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:customersTableName}

    OrdersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: orderId
            AttributeType: S
        KeySchema:
          - AttributeName: orderId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:ordersTableName}
